
import java.io.*;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lolihuntz
 */
public class MainApllication extends javax.swing.JFrame {
    Prepare next_prepare;
    deckwindow deckview;
    Credit next_credit;
    int next_prepare_x = 400;
    int next_prepare_y = 200;
    int next_deckview_x = 0;
    int next_deckview_y = 0;
    int next_credit_x = 0;
    int next_credit_y = 0;
    /**
     * Creates new form main
     */
    public MainApllication() {
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        play = new javax.swing.JLabel();
        viewdeck = new javax.swing.JLabel();
        credit = new javax.swing.JLabel();
        project_name1 = new javax.swing.JLabel();
        project_name = new javax.swing.JLabel();
        line = new javax.swing.JLabel();
        moon = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        play.setBackground(new java.awt.Color(255, 255, 255));
        play.setFont(new java.awt.Font("DRdeco", 1, 24)); // NOI18N
        play.setForeground(new java.awt.Color(255, 255, 255));
        play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        play.setText("play");
        play.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        play.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playMouseExited(evt);
            }
        });
        jPanel1.add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 269, 70));

        viewdeck.setBackground(new java.awt.Color(255, 255, 255));
        viewdeck.setFont(new java.awt.Font("DRdeco", 1, 24)); // NOI18N
        viewdeck.setForeground(new java.awt.Color(255, 255, 255));
        viewdeck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewdeck.setText("view deck");
        viewdeck.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewdeck.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewdeck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewdeckMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewdeckMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewdeckMouseExited(evt);
            }
        });
        jPanel1.add(viewdeck, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 269, 70));

        credit.setBackground(new java.awt.Color(255, 255, 255));
        credit.setFont(new java.awt.Font("DRdeco", 1, 24)); // NOI18N
        credit.setForeground(new java.awt.Color(255, 255, 255));
        credit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        credit.setText("credit");
        credit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        credit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        credit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creditMouseExited(evt);
            }
        });
        jPanel1.add(credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 269, 70));

        project_name1.setFont(new java.awt.Font("DRdeco", 1, 72)); // NOI18N
        project_name1.setForeground(new java.awt.Color(255, 255, 255));
        project_name1.setText("project");
        jPanel1.add(project_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 400, 70));

        project_name.setFont(new java.awt.Font("DRdeco", 1, 72)); // NOI18N
        project_name.setForeground(new java.awt.Color(255, 255, 255));
        project_name.setText("            z");
        jPanel1.add(project_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 400, 70));

        line.setBackground(new java.awt.Color(255, 255, 255));
        line.setOpaque(true);
        jPanel1.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 560, 10));

        moon.setBackground(new java.awt.Color(255, 255, 153));
        moon.setIcon(new javax.swing.ImageIcon("resource/bg/MOON.gif"));
        jPanel1.add(moon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 540, 486));

        background.setIcon(new javax.swing.ImageIcon("resource/bg/MAIN_MENU.gif"));
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseClicked
        // TODO add your handling code here:
        if(next_prepare == null){    
            next_prepare = new Prepare();
            next_prepare.setLocation(next_prepare_x, next_prepare_y);
        }
        else
            next_prepare.setNotReady();
        String[] newList = null;
        try{
            String line = "";
            Scanner scan = new Scanner(new File("ALL_DECKS_NAME.txt"));
            while(scan.hasNext()){
                line += scan.nextLine();
            };
            newList = line.split(",");
        }
        catch(FileNotFoundException e){
            System.out.print(e.getMessage());
        }
        next_prepare.setDeck(newList);
        next_prepare.setVisible(true);
    }//GEN-LAST:event_playMouseClicked

    private void playMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseEntered
        // TODO add your handling code here:
        play.setOpaque(true);
        play.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_playMouseEntered

    private void playMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseExited
        // TODO add your handling code here:
        play.setOpaque(false);
        play.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_playMouseExited

    private void viewdeckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewdeckMouseEntered
        // TODO add your handling code here:
        viewdeck.setOpaque(true);
        viewdeck.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_viewdeckMouseEntered

    private void viewdeckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewdeckMouseExited
        // TODO add your handling code here:
        viewdeck.setOpaque(false);
        viewdeck.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_viewdeckMouseExited

    private void viewdeckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewdeckMouseClicked
        // TODO add your handling code here:
        if(deckview == null){
            deckview = new deckwindow();
            deckview.setLocation(next_deckview_x, next_deckview_y);
        }
        deckview.setVisible(true);
    }//GEN-LAST:event_viewdeckMouseClicked

    private void creditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditMouseClicked
        // TODO add your handling code here:
        if(next_credit == null){
            next_credit = new Credit();
            next_credit.setLocation(next_credit_x, next_credit_y);
        }
        next_credit.setVisible(true);
    }//GEN-LAST:event_creditMouseClicked

    private void creditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditMouseEntered
        // TODO add your handling code here:
        credit.setOpaque(true);
        credit.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_creditMouseEntered

    private void creditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditMouseExited
        // TODO add your handling code here:
        credit.setOpaque(false);
        credit.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_creditMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApllication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApllication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApllication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApllication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        File directory = new File(System.getProperty("user.dir")+"/deck"); 
        String[] allFile = directory.list();
                if(allFile != null){
                    try{
                        FileWriter fw = new FileWriter(new File("ALL_DECKS_NAME.txt"));
                        for(int i=0;i<allFile.length;i++){
                            String temp = allFile[i].substring(0,allFile[i].length()-4);
                            fw.write(temp+",\n");
                        }
                        fw.close();
                    }
                    catch(FileNotFoundException ex){
                        System.out.println(ex);
                    }
                    catch(IOException ex){
                        System.out.println(ex);
                    }
                }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApllication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel credit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel line;
    private javax.swing.JLabel moon;
    private javax.swing.JLabel play;
    private javax.swing.JLabel project_name;
    private javax.swing.JLabel project_name1;
    private javax.swing.JLabel viewdeck;
    // End of variables declaration//GEN-END:variables
}
