

import java.io.*;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lolihuntz
 */
public class Prepare extends javax.swing.JFrame {
    private boolean player1_firstclicked = false;
    private boolean player2_firstclicked = false;
    private Play next_play;
    private int next_play_x = 0;
    private int next_play_y = 0;
    private String[] list;
    boolean isEnd=false;
    
    /**
     * Creates new form Prepare
     */
    public Prepare() {
        try{
            String line = "";
            Scanner scan = new Scanner(new File("ALL_DECKS_NAME.txt"));
            while(scan.hasNext()){
                line += scan.nextLine();
            };
            list = line.split(",");
        }
        catch(FileNotFoundException e){
            System.out.print(e.getMessage());
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        line = new javax.swing.JLabel();
        player1 = new javax.swing.JTextField();
        player2 = new javax.swing.JTextField();
        deck2 = new javax.swing.JComboBox<>();
        deck1 = new javax.swing.JComboBox<>();
        ready1 = new javax.swing.JCheckBox();
        ready2 = new javax.swing.JCheckBox();
        start = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prepare");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 477));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 477));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        line.setBackground(new java.awt.Color(255, 255, 255));
        line.setOpaque(true);
        jPanel1.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 5));

        player1.setFont(new java.awt.Font("DRdeco", 0, 24)); // NOI18N
        player1.setForeground(new java.awt.Color(153, 153, 153));
        player1.setText("player1");
        player1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1MouseClicked(evt);
            }
        });
        jPanel1.add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, -1));

        player2.setFont(new java.awt.Font("DRdeco", 0, 24)); // NOI18N
        player2.setForeground(new java.awt.Color(153, 153, 153));
        player2.setText("player2");
        player2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2MouseClicked(evt);
            }
        });
        jPanel1.add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, -1));

        deck2.setFont(new java.awt.Font("DRdeco", 1, 14)); // NOI18N
        deck2.setModel(new javax.swing.DefaultComboBoxModel<>(list));
        deck2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deck2ActionPerformed(evt);
            }
        });
        jPanel1.add(deck2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 150, 50));

        deck1.setFont(new java.awt.Font("DRdeco", 1, 14)); // NOI18N
        deck1.setModel(new javax.swing.DefaultComboBoxModel<>(list));
        jPanel1.add(deck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 150, 50));

        ready1.setFont(new java.awt.Font("DRdeco", 1, 18)); // NOI18N
        ready1.setText("ready");
        ready1.setOpaque(false);
        ready1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ready1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ready1MouseExited(evt);
            }
        });
        jPanel1.add(ready1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        ready2.setFont(new java.awt.Font("DRdeco", 1, 18)); // NOI18N
        ready2.setText("ready");
        ready2.setOpaque(false);
        ready2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ready2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ready2MouseExited(evt);
            }
        });
        jPanel1.add(ready2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        start.setBackground(new java.awt.Color(255, 255, 255));
        start.setFont(new java.awt.Font("DRdeco", 1, 18)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        start.setText("Start");
        start.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        start.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startMouseExited(evt);
            }
        });
        jPanel1.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 170, 50));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("DRdeco", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("back");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 170, 50));

        label1.setFont(new java.awt.Font("DRdeco", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Prepare");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, -1));

        label3.setFont(new java.awt.Font("DRdeco", 1, 24)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("deck");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        label2.setFont(new java.awt.Font("DRdeco", 1, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("name");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon("resource/bg/PREPARE.gif"));
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseEntered
        // TODO add your handling code here:
        start.setOpaque(true);
        start.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_startMouseEntered

    private void startMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseExited
        // TODO add your handling code here:
        start.setOpaque(false);
        start.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_startMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setOpaque(true);
        back.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setOpaque(false);
        back.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_backMouseExited

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
        // TODO add your handling code here:
        int op=JOptionPane.YES_OPTION;
        if(next_play!=null&&next_play.isGameEnd()){
            clearPlay();
        }
        if(next_play == null){
            if(ready1.isSelected() && ready2.isSelected()){
                int index1 = deck1.getSelectedIndex();
                int index2 = deck2.getSelectedIndex();
                String deckname1 = list[index1];
                String deckname2 = list[index2];
                System.out.println(deckname1+" and "+deckname2);
                var source1 = new File(System.getProperty("user.dir")+"/deck/"+deckname1+".txt");
                var source2 = new File(System.getProperty("user.dir")+"/deck/"+deckname2+".txt");
                var dest1 = new File("deck1.txt");
                var dest2 = new File("deck2.txt");
                try{
                Files.copy(source1.toPath(), dest1.toPath(),
                    StandardCopyOption.REPLACE_EXISTING);
                Files.copy(source2.toPath(), dest2.toPath(),
                    StandardCopyOption.REPLACE_EXISTING);
                }
                catch(FileNotFoundException ex){
                        System.out.println(ex);
                }
                catch(IOException ex){
                    System.out.println(ex);
                }
                next_play = new Play(player1.getText(), player2.getText(), deckname1, deckname2);
                next_play.setVisible(true);
                next_play.setLocation(next_play_x, next_play_y);
            }
            else{
                //print can't
            }
        }
        else{
                if(ready1.isSelected() && ready2.isSelected()){
                op = JOptionPane.showConfirmDialog(null,"The lastest game is already playing, Do you want to continue ?","Warning!",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
                if(op == JOptionPane.YES_OPTION)
                    next_play.setVisible(true);
                else{
                    op = JOptionPane.showConfirmDialog(null,"Do you want to start a new game ?","Warning!",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
                    if(op == JOptionPane.YES_OPTION){
                    int index1 = deck1.getSelectedIndex();
                    int index2 = deck2.getSelectedIndex();
                    String deckname1 = list[index1];
                    String deckname2 = list[index2];
                    System.out.println(deckname1+" and "+deckname2);
                    var source1 = new File(System.getProperty("user.dir")+"/deck/"+deckname1+".txt");
                    var source2 = new File(System.getProperty("user.dir")+"/deck/"+deckname2+".txt");
                    var dest1 = new File("deck1.txt");
                    var dest2 = new File("deck2.txt");
                    try{
                    Files.copy(source1.toPath(), dest1.toPath(),
                        StandardCopyOption.REPLACE_EXISTING);
                    Files.copy(source2.toPath(), dest2.toPath(),
                        StandardCopyOption.REPLACE_EXISTING);
                    }
                    catch(FileNotFoundException ex){
                        System.out.println(ex);
                    }
                    catch(IOException ex){
                        System.out.println(ex);
                    }
                    next_play = new Play(player1.getText(), player2.getText(), deckname1, deckname2);
                    next_play.setVisible(true);
                    next_play.setLocation(next_play_x, next_play_y);
                    }
                }
            }
        }
        if(ready1.isSelected() && ready2.isSelected()&&op==JOptionPane.YES_OPTION){
            this.dispose();
            isEnd=true;
        }
    }//GEN-LAST:event_startMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backMouseClicked

    private void ready1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ready1MouseEntered
        // TODO add your handling code here:
        ready1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_ready1MouseEntered

    private void ready1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ready1MouseExited
        // TODO add your handling code here:
        ready1.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_ready1MouseExited

    private void ready2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ready2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ready2MouseEntered

    private void ready2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ready2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ready2MouseExited

    private void player1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1MouseClicked
        // TODO add your handling code here:
        if(player1_firstclicked == false){
            player1_firstclicked = true;
            player1.setText("");
        }
    }//GEN-LAST:event_player1MouseClicked

    private void player2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2MouseClicked
        // TODO add your handling code here:
        if(player2_firstclicked == false){
            player2_firstclicked = true;
            player2.setText("");
        }
    }//GEN-LAST:event_player2MouseClicked

    private void deck2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deck2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deck2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prepare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prepare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prepare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prepare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prepare().setVisible(true);
            }
        });
    }
    
    public void setdeckname(int index){
        /*if(index == 1){
            deckname 
        }*/
    }
    public void setDeck(String[] newList){
        list = newList.clone();
        deck1.setModel(new javax.swing.DefaultComboBoxModel<>(list));
        deck2.setModel(new javax.swing.DefaultComboBoxModel<>(list));
        repaint();
        validate();
    }
    public void clearPlay(){
        next_play = null;
    }
    public boolean checkEnd(){
        return isEnd;
    }
    public void setNotReady(){
        ready1.setSelected(false);
        ready2.setSelected(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> deck1;
    private javax.swing.JComboBox<String> deck2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel line;
    private javax.swing.JTextField player1;
    private javax.swing.JTextField player2;
    private javax.swing.JCheckBox ready1;
    private javax.swing.JCheckBox ready2;
    private javax.swing.JLabel start;
    // End of variables declaration//GEN-END:variables
}
